version: '3.4'

services:
  db:
    image: "postgres" # use latest official postgres version
    ports:
      - "25432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose